version: '3.8'

services:
  db:
    image: postgres:14.1-alpine
    env_file:
      - .env
    environment:
      TZ: UTC
      PGTZ: UTC
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - './api/tmp/db:/var/lib/postgresql/data'

  api:
    build:
      context: ./api
      env_file:
        - .env
      args:
        WORKDIR: $WORKDIR
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - './api:/$WORKDIR'
    depends_on:
      - db
    ports:
      - '$API_PORT:3000'

  front:
    build:
      context: ./front
      env_file:
        - .env
      args:
        WORKDIR: $WORKDIR
    command: yarn run dev
    volumes:
      - './front:/$WORKDIR'
    ports:
      - '$FRONT_PORT:3000'
    depends_on:
      - api
