version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.2
        environment:
          POSTGRES_USER: postgres
          PGHOST: 127.0.0.1
          RAILS_ENV: test
      - image: circleci/postgres:latest-postgis
        environment:
          POSTGRES_USER: postgres
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_DB: app_test
    working_directory: ~/docker_wonderful
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            gem install bundler -v 2.1.4
            bundle install --path vendor/bundle --jobs 4

      - save_cache:
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
          paths:
            - ./vendor/bundle

      - run:
          name: DBの起動を待つ
          command: dockerize -wait tcp://127.0.0.1:5432 -timeout 120s

      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load

      - run:
          name: rspecを実行
          command: bundle exec rspec
