version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.2
        environment:
          POSTGRES_USER: postgres
          PGHOST: '127.0.0.1'
          RAILS_ENV: test

      - image: circleci/postgres:9.6
        environment:
          POSTGRES_USER: postgres
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_DB: app_test

    working_directory: ~/docker_wonderful/api
    steps:
      - checkout:
          path: ~/docker_wonderful

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            gem install bundler
            bundle install

      - save_cache:
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
          paths:
            - ./vendor/bundle

      - run:
          name: DBの起動を待つ
          command: dockerize -wait tcp://127.0.0.1:5432 -timeout 120s

      - run: mv config/database.yml.ci config/database.yml
      - run: bundle exec rails db:create
      - run: bundle exec rails db:schema:load

      - run:
          name: rspecを実行
          command: bundle exec rspec

      - run:
          name: rubocopを実行
          command: bundle exec rubocop
