version: 2.1
jobs:
  build:
    docker:
      #アプリのバージョンを指定
      - image: circleci/ruby:2.7.2
        environment:
          #自身の登録しているユーザに変える。
          POSTGRES_USER: postgres
          PGHOST: 127.0.0.1
          RAILS_ENV: test
      #使ってるデータベースとバージョンを指定する。# 「host: localhost」でアクセスできるサービスコンテナイメージ。
      - image: circleci/postgres:9.6
        environment:
          #それぞれ設定
          POSTGRES_USER: postgres
          #下記を書けばパスワードなしでデータベースにログインしてくれる。
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_DB: app_test
    #自身のアプリ名にする
    working_directory: ~/docker_wonderful/api
    steps:
      - checkout
      #bundle キャッシュをリストアする。公式の設定通り。
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "api/Gemfile.lock" }}
            - v1-dependencies-
      # bundle install で依存関係をインストールする。公式の設定と多少異なってます。
      - run:
          name: install dependencies
          command: |
            gem install bundler
            bundle config set --local path 'docker_wonderful/api'
            bundle install

      # bundle キャッシュを保存する。公式の設定通り。
      - save_cache:
          key: v1-dependencies-{{ checksum "api/Gemfile.lock" }}
          paths:
            - ./vendor/bundle

      #↓追加する
      - run:
          name: DBの起動を待つ
          command: dockerize -wait tcp://127.0.0.1:5432 -timeout 120s

      - run: bundle exec rails db:create
      - run: bundle exec rails db:schema:load

      # rspecを実行する
      - run:
          name: rspecを実行
          command: bundle exec rspec
